# Generated by Django 5.1.4 on 2024-12-05 19:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('vulnerability', 'Vulnerabilidade'), ('data_breach', 'Vazamento de dados'), ('other', 'Outro')], max_length=50)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em analise'), ('resolved', 'Resolvido')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
